// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_common.proto

package service_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetLogLevelReq struct {
	Level                uint32   `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLogLevelReq) Reset()         { *m = SetLogLevelReq{} }
func (m *SetLogLevelReq) String() string { return proto.CompactTextString(m) }
func (*SetLogLevelReq) ProtoMessage()    {}
func (*SetLogLevelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{0}
}

func (m *SetLogLevelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLogLevelReq.Unmarshal(m, b)
}
func (m *SetLogLevelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLogLevelReq.Marshal(b, m, deterministic)
}
func (m *SetLogLevelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLogLevelReq.Merge(m, src)
}
func (m *SetLogLevelReq) XXX_Size() int {
	return xxx_messageInfo_SetLogLevelReq.Size(m)
}
func (m *SetLogLevelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLogLevelReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetLogLevelReq proto.InternalMessageInfo

func (m *SetLogLevelReq) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type SetLogLevelAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLogLevelAck) Reset()         { *m = SetLogLevelAck{} }
func (m *SetLogLevelAck) String() string { return proto.CompactTextString(m) }
func (*SetLogLevelAck) ProtoMessage()    {}
func (*SetLogLevelAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{1}
}

func (m *SetLogLevelAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLogLevelAck.Unmarshal(m, b)
}
func (m *SetLogLevelAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLogLevelAck.Marshal(b, m, deterministic)
}
func (m *SetLogLevelAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLogLevelAck.Merge(m, src)
}
func (m *SetLogLevelAck) XXX_Size() int {
	return xxx_messageInfo_SetLogLevelAck.Size(m)
}
func (m *SetLogLevelAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLogLevelAck.DiscardUnknown(m)
}

var xxx_messageInfo_SetLogLevelAck proto.InternalMessageInfo

type ServerStateCheckReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStateCheckReq) Reset()         { *m = ServerStateCheckReq{} }
func (m *ServerStateCheckReq) String() string { return proto.CompactTextString(m) }
func (*ServerStateCheckReq) ProtoMessage()    {}
func (*ServerStateCheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{2}
}

func (m *ServerStateCheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStateCheckReq.Unmarshal(m, b)
}
func (m *ServerStateCheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStateCheckReq.Marshal(b, m, deterministic)
}
func (m *ServerStateCheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStateCheckReq.Merge(m, src)
}
func (m *ServerStateCheckReq) XXX_Size() int {
	return xxx_messageInfo_ServerStateCheckReq.Size(m)
}
func (m *ServerStateCheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStateCheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStateCheckReq proto.InternalMessageInfo

type ServerStateCheckAck struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStateCheckAck) Reset()         { *m = ServerStateCheckAck{} }
func (m *ServerStateCheckAck) String() string { return proto.CompactTextString(m) }
func (*ServerStateCheckAck) ProtoMessage()    {}
func (*ServerStateCheckAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{3}
}

func (m *ServerStateCheckAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStateCheckAck.Unmarshal(m, b)
}
func (m *ServerStateCheckAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStateCheckAck.Marshal(b, m, deterministic)
}
func (m *ServerStateCheckAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStateCheckAck.Merge(m, src)
}
func (m *ServerStateCheckAck) XXX_Size() int {
	return xxx_messageInfo_ServerStateCheckAck.Size(m)
}
func (m *ServerStateCheckAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStateCheckAck.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStateCheckAck proto.InternalMessageInfo

func (m *ServerStateCheckAck) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type KeepAliveReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveReq) Reset()         { *m = KeepAliveReq{} }
func (m *KeepAliveReq) String() string { return proto.CompactTextString(m) }
func (*KeepAliveReq) ProtoMessage()    {}
func (*KeepAliveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{4}
}

func (m *KeepAliveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveReq.Unmarshal(m, b)
}
func (m *KeepAliveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveReq.Marshal(b, m, deterministic)
}
func (m *KeepAliveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveReq.Merge(m, src)
}
func (m *KeepAliveReq) XXX_Size() int {
	return xxx_messageInfo_KeepAliveReq.Size(m)
}
func (m *KeepAliveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveReq proto.InternalMessageInfo

type KeepAliveAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveAck) Reset()         { *m = KeepAliveAck{} }
func (m *KeepAliveAck) String() string { return proto.CompactTextString(m) }
func (*KeepAliveAck) ProtoMessage()    {}
func (*KeepAliveAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fef5d01073a7a3, []int{5}
}

func (m *KeepAliveAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveAck.Unmarshal(m, b)
}
func (m *KeepAliveAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveAck.Marshal(b, m, deterministic)
}
func (m *KeepAliveAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveAck.Merge(m, src)
}
func (m *KeepAliveAck) XXX_Size() int {
	return xxx_messageInfo_KeepAliveAck.Size(m)
}
func (m *KeepAliveAck) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveAck.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveAck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SetLogLevelReq)(nil), "service_common.SetLogLevelReq")
	proto.RegisterType((*SetLogLevelAck)(nil), "service_common.SetLogLevelAck")
	proto.RegisterType((*ServerStateCheckReq)(nil), "service_common.ServerStateCheckReq")
	proto.RegisterType((*ServerStateCheckAck)(nil), "service_common.ServerStateCheckAck")
	proto.RegisterType((*KeepAliveReq)(nil), "service_common.KeepAliveReq")
	proto.RegisterType((*KeepAliveAck)(nil), "service_common.KeepAliveAck")
}

func init() { proto.RegisterFile("service_common.proto", fileDescriptor_53fef5d01073a7a3) }

var fileDescriptor_53fef5d01073a7a3 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x52, 0xe3, 0xe2, 0x0b, 0x4e, 0x2d, 0xf1, 0xc9, 0x4f, 0xf7, 0x49,
	0x2d, 0x4b, 0xcd, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe1, 0x62, 0xcd, 0x01, 0xb1, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x83, 0x20, 0x1c, 0x25, 0x01, 0x14, 0x75, 0x8e, 0xc9, 0xd9, 0x4a, 0xa2, 0x5c,
	0xc2, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc1, 0x25, 0x89, 0x25, 0xa9, 0xce, 0x19, 0xa9, 0xc9,
	0xd9, 0x41, 0xa9, 0x85, 0x4a, 0xea, 0x98, 0xc2, 0x8e, 0xc9, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xa9,
	0x45, 0x45, 0x60, 0x33, 0x39, 0x83, 0x40, 0x4c, 0x25, 0x3e, 0x2e, 0x1e, 0xef, 0xd4, 0xd4, 0x02,
	0xc7, 0x9c, 0xcc, 0xb2, 0x54, 0x90, 0x46, 0x64, 0xbe, 0x63, 0x72, 0x76, 0x12, 0x1b, 0xd8, 0xc1,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xa7, 0xae, 0x31, 0xc8, 0x00, 0x00, 0x00,
}
